### ISSUE TITLE
BREAK statement not caught

### ISSUE THREAD

**Issue by EduardoCopat** [larshp/abaplint#112]
**BREAK** statement is not being catch.  Code inspector checks this ( see http://www.kodyaz.com/sap-abap/break-point-pragma-for-sap-code-inspector.aspx ). 

Example:
`BREAK copat.`

To reproduce:

Open https://larshp.github.io/abaplint/
Add `BREAK user` after line 5.
Check for issues.
No issues for break.

Also reproduced at this commit (BREAK not caught)

https://travis-ci.org/EduardoCopat/abapGit/builds/177047575

**Comment by larshp** [comment]
yeah, that would be a new rule, lots of new things to add to abaplint :smile: 

also `BREAK-POINT` is not caught, https://github.com/larshp/abaplint/issues/110

**Comment by larshp** [comment]
fixed, new version released to npm
