### ISSUE TITLE
Parser error: MODIFY (itab) FROM (struct) TRANSPORTING (fields) WHERE (cond)

### ISSUE THREAD

**Issue by Ironus** [larshp/abaplint#178]
Hi,

In the Atom version of the linter there is a parser error if there is TRANSPORTING or WHERE condition in the MODIFY statement.
Please find the attachment with faulty code.

Best regards,
Ironus

Attachments:
[parserErrors.txt](https://github.com/larshp/abaplint/files/1130756/parserErrors.txt)

**Comment by larshp** [comment]
You can try the latest version at:
https://larshp.github.io/abaplint/
it looks like it works

I think the Atom package is running on an old version of abaplint see https://github.com/larshp/linter-abaplint/issues/8

**Comment by larshp** [comment]
@Ironus try again, linter-abaplint 0.13 released

**Comment by Ironus** [comment]
Works like a charm. Thank you!
