### ISSUE TITLE
Parser error on interface with ignore default

### ISSUE THREAD

**Issue by Gekke-Jakke** [larshp/abaplint#181]
When parsing an interface I get following parser errors:
![image](https://user-images.githubusercontent.com/2744548/29230091-b618dd28-7ee1-11e7-8472-6883a4a4a060.png)

I think these are related to following properties that can be enabled:
![image](https://user-images.githubusercontent.com/2744548/29230171-102248ea-7ee2-11e7-8ada-2ca62bf5c808.png)

By activating these properties following statements are added to the interfact definition:
![image](https://user-images.githubusercontent.com/2744548/29230213-36fd05d6-7ee2-11e7-9955-fa59016e295e.png)

**Comment by larshp** [comment]
@Gekke-Jakke try again, version 0.29.18

https://larshp.github.io/abaplint/viz/methoddef.svg

**Comment by Gekke-Jakke** [comment]
@larshp Works perfectly! Thanks for the update!
