### ISSUE TITLE
Support new OpenSQL instructions (@ character)

### ISSUE THREAD

**Issue by EduardoCopat** [larshp/abaplint#192]
When using [new OpenSQL instructions](https://help.sap.com/doc/abapdocu_751_index_htm/7.51/en-US/abapinto_clause.htm), I receive a parser error.

See example below. When using the `@` character, you need to separate the select fields using `,`.

```abap
CLASS zflight_repository DEFINITION
  PUBLIC
  FINAL
  CREATE PUBLIC .

  PUBLIC SECTION.
    METHODS read
      IMPORTING
        i_flight_number TYPE sflight-carrid
      RETURNING
        VALUE(return)   TYPE sflight.

  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.

CLASS zflight_repository IMPLEMENTATION.
  METHOD read.
    SELECT SINGLE carrid, connid, fldate FROM sflight
      INTO CORRESPONDING FIELDS OF @return
      WHERE carrid = @i_flight_number.
  ENDMETHOD.
ENDCLASS.
```

Error:

`​[19, 5] Parser error(Unknown statement)`

**P.S.:** Is there a way to annotate a statement where abaplint ignores it? Similar to `"#EC NEEDED` in code inspector.

**Comment by larshp** [comment]
thanks

annotate: no currently not

**Comment by larshp** [comment]
some of the @ should work, https://larshp.github.io/abaplint/viz/reuse_select.svg

**Comment by larshp** [comment]
@EduardoCopat try again, latest version, 0.29.22

**Comment by EduardoCopat** [comment]
It's working now 👍
