### ISSUE TITLE
Parser error with multiple row VALUE

### ISSUE THREAD

**Issue by EduardoCopat** [larshp/abaplint#195]
See example:

`DATA(foo) = VALUE #( ( '20' ) ( '30' ) ).`

Also happens without in-line `DATA`

```
DATA foo type tstrings.
foo = VALUE #( ( '20' ) ( '30' ) ).
```

Not sure if connected to #194

**Comment by larshp** [comment]
already have an existing commented test case, https://github.com/larshp/abaplint/blob/master/test/statements/move.ts#L95

this might be a difficult one

**Comment by larshp** [comment]
try again, version 0.29.23
