### ISSUE TITLE
FOR ALL ENTRIES and new SQL @ notation

### ISSUE THREAD

**Issue by EduardoCopat** [larshp/abaplint#196]
Parser error when doing a `FOR ALL ENTRIES` against an internal table, when using the `@` escape notation:

```abap
DATA: flight type table of sflight.
data: carriers type table of scarr.

SELECT carrid, connid FROM sflight INTO CORRESPONDING FIELDS OF TABLE @flight
FOR ALL ENTRIES IN @carriers.
```

**Comment by larshp** [comment]
node with `!" @"` has to be added after FOR ALL ENTRIES in https://larshp.github.io/abaplint/viz/reuse_select.svg

perhaps make a new reuse element, SQLSource and SQLTarget

**Comment by larshp** [comment]
try again, version 0.29.23
