### ISSUE TITLE
configuration documentation

### ISSUE THREAD

**Issue by JohannesKonings** [larshp/abaplint#217]
Where can we document how abaplint can be configured?

- In the [README.md](https://github.com/larshp/abaplint/blob/master/README.md)?

- In the [Wiki](https://github.com/larshp/abaplint/wiki)?

- In the [docs](https://github.com/larshp/abaplint/issues/163)

- somewhere else?

https://abapgit.slack.com/archives/C4K5GM9D0/p1531310895000226
![image](https://user-images.githubusercontent.com/14806640/42598848-b0cc1302-855d-11e8-9a3f-c35b2dbcc78f.png)

**Comment by larshp** [comment]
would like to move all documentation to a docs folder, https://github.com/larshp/abaplint/issues/163

**Comment by JohannesKonings** [comment]
done with https://github.com/larshp/abaplint/issues/163
