### ISSUE TITLE
subquery is not supported

### ISSUE THREAD

**Issue by PShumilov** [larshp/abaplint#263]
Please add subquery constructions like these:
```
( select )   
ALL ( select )   
ANY ( select )  
SOME ( select )
```

**Comment by larshp** [comment]
yeah, lots of bugs

never used the subquery ALL SOME ANY 😄 

https://help.sap.com/doc/abapdocu_750_index_htm/7.50/en-US/abenwhere_logexp_all_any_some.htm

can you help adding a full statement examples in this issue? It can be used for the unit tests

**Comment by PShumilov** [comment]
Examples from demo programms:

> If using ALL, the expression is true if the comparison is true for all rows in the results set of the scalar subquery.
> If the addition ANY or SOME is used, the expression is true if it is true for at least one of the rows in the results set of the subquery.

Example 1
Correlated, non-scalar subquery:
```
SELECT  carrname
  INTO  TABLE name_tab
  FROM  scarr
  WHERE EXISTS ( select  *
                   FROM  spfli
                   WHERE carrid   =  scarr~carrid AND
                         cityfrom = 'NEW YORK'        ).
```
Example 2                        
Scalar subquery:
```
DATA: carr_id TYPE spfli-carrid VALUE 'LH',
      conn_id TYPE spfli-connid VALUE '0400'.

DATA: city  TYPE sgeocity-city,
      lati  TYPE p DECIMALS 2,
      longi TYPE p DECIMALS 2.

SELECT  SINGLE city latitude longitude
  INTO  (city, lati, longi)
  FROM  sgeocity
  WHERE city IN ( select  cityfrom
                    FROM  spfli
                    WHERE carrid = carr_id AND
                          connid = conn_id      ).
```
Example 3
```
DATA: wa TYPE sflight,
      plane LIKE wa-planetype,
      seats LIKE wa-seatsmax.

SELECT     carrid connid planetype seatsmax MAX( seatsocc )
  INTO     (wa-carrid, wa-connid, wa-planetype,
            wa-seatsmax, wa-seatsocc)
  FROM     sflight
  GROUP BY carrid connid planetype seatsmax
  ORDER BY carrid connid.

*  WRITE: 

ENDSELECT.
...

SELECT  planetype seatsmax
  INTO  (plane, seats)
  FROM  saplane AS plane
  WHERE seatsmax < wa-seatsmax AND
        seatsmax >= ALL ( select  seatsocc
                            FROM  sflight
                            WHERE carrid = wa-carrid AND
                                  connid = wa-connid     )
  ORDER BY seatsmax.

*  WRITE: 

ENDSELECT.
```
Another examples:
> Sometimes you just want to know whether some records in a secondary table exist or not. You don‘t need their actual content.
> This is where Subqueries come in handy:
> Are there any rows in the SFLIGHT table without a corresponding entry in table SPFLI?
```
SELECT carrid connid
  INTO (xcarrid, xconnid)
  FROM sflight AS f
  WHERE NOT EXISTS ( SELECT * FROM spfli
                      WHERE carrid = f~carrid
                        AND connid = f~connid ).
```
More interesting example written by me:
```
DATA lt_pernr TYPE TABLE OF persno.
DATA dyn_cond TYPE string.

SELECT  pernr FROM pa0002 INTO TABLE lt_pernr UP TO 100 ROWS
  WHERE pernr = SOME ( select pernr FROM pa9510
                        WHERE code_facet IN ( select facet~ccode 
                                                FROM t7ruokinfacet AS facet
                                                JOIN t7ruokin      AS okin
                                                  ON facet~ccode = okin~facet
                                               WHERE (dyn_cond) ) ).
```
'dyn_cond' can contain a condition or even  another one subquery :smile: 
Are examples like these enough? If you need another one with sertain expressions I'll try to do it. 
Hope, it's helpful.

**Comment by larshp** [comment]
it helps, thanks 👍 

might have some time during the weekend. Until then #SAPTechEd

**Comment by larshp** [comment]
do you know which abap versions support the above statements? I guess it was somewhere after 702?

**Comment by larshp** [comment]
Example 1 already works

**Comment by larshp** [comment]
@PShumilov try again, version 1.1.2 released

**Comment by PShumilov** [comment]
> do you know which abap versions support the above statements? I guess it was somewhere after 702?

I use it in version 620

**Comment by larshp** [comment]
oh, okay, then it is an old feature 😄 

did you try the latest abaplint version?

**Comment by PShumilov** [comment]
I've just tried the latest abaplint version. Examples 1,2 is ok, for others doesn't work

**Comment by larshp** [comment]
Try pasting the code into https://playground.abaplint.org and click issues, seems to work there? How are you running abaplint? Some of the tools like the atom and vscode plugins are not updated to use the latest, plus try removing your package-lock file if installed via npm.

![image](https://user-images.githubusercontent.com/5888506/47700209-f3f2ce00-dc15-11e8-8ce6-676a5f36fc1a.png)

**Comment by PShumilov** [comment]
I use vs code plugin. I've just tried the web abaplint. Everything is working now. Good job! Thanks! :+1:
