### ISSUE TITLE
npm run scripts dont find abaplint

### ISSUE THREAD

**Issue by sbcgua** [larshp/abaplint#297]
e.g. running `npm test pretest` in ag folder under windows will give

```
Path not found
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @ pretest: `abaplint --version && abaplint "src/**/*.abap"`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @ pretest script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```
same can be done in abaplint repo itself. E.g. I add "chk" script to package.json which would just call "abaplint", then call `npm link` and `npm run chk` and get the same error

My guess is that it is because `./abaplint` header

```
#!/bin/sh
":" //# comment; exec /usr/bin/env node "$0" "$@"
require("./build/src/cli");
```

If I change it to a more common 

```
#!/usr/bin/env node
require("./build/src/cli");
```

all works fine

**Comment by larshp** [comment]
Unable to reproduce, I get an error, but not the above, plus changing the file to the common approach also does not seem to work,
![image](https://user-images.githubusercontent.com/5888506/50159226-7fafdf00-02d6-11e9-8b00-18e8baba26f8.png)

**Comment by sbcgua** [comment]
try `npm run pretest` or `npm run lint`
The error seems to be the same - I just have another locale so `Path not found` is my translation :) And my output is more verbose but starts with the same error message

**Comment by sbcgua** [comment]
UPD: yes for `npm test` it looks like your's.

**Comment by larshp** [comment]
okay 👍 

calling abaplint directly works, need something where its possible to enable worker threads( `--experimental-worker` )

not sure its possible to get it working nicely until its enabled by default in node

**Comment by sbcgua** [comment]
works now ! closing.
