### ISSUE TITLE
npm package-lock.json strategy

### ISSUE THREAD

**Issue by sbcgua** [larshp/abaplint#300]
currently package-lock.json is not tracked by git. Although it is recommended.
Propose either to remove the ignore or add `.npmrc` with  `package-lock=false` to avoid file generation.
Just as a "best practice".

**Comment by larshp** [comment]
yeah, I'm just lazy 😄

**Comment by sbcgua** [comment]
=)) I can commit 
But ... npmrc or remove ignore ? I'd actually lock to the repo ... 
I think greenkeeper may know how to update it automatically ... though I never used it before
