### ISSUE TITLE
npm test test ends with 25 error code ELIFECYCLE

### ISSUE THREAD

**Issue by zapik** [larshp/abaplint#303]
I am trying to install this on windows 10, node v10.14.2

npm install 

audited 1266 packages in 6.395s 
found 0 vulnerabilities

npm test 

...
> abaplint@1.5.1 compile C:\Users\I070772\git\abaplint
> tsc --pretty

src/cli.ts:71:12 - error TS2709: Cannot use namespace 'ProgressBar' as a type.
71   let bar: ProgressBar | undefined = undefined;

src/cli.ts:74:11 - error TS2351: Cannot use 'new' with an expression whose type lacks a call or construct signature.
74     bar = new ProgressBar(":percent - :elapseds - Reading files - :filename", {total: input.length});

src/cli.ts:175:16 - error TS2709: Cannot use namespace 'ProgressBar' as a type.
175   private bar: ProgressBar;

src/cli.ts:178:16 - error TS2351: Cannot use 'new' with an expression whose type lacks a call or construct signature.
178     this.bar = new ProgressBar(text, {total, renderThrottle: 100});

Or should I perform some additional steps?

**Comment by larshp** [comment]
yeah, getting the same error in https://github.com/larshp/abaplint/issues/302

guess something new is called ProgressBar in vanilla node

**Comment by larshp** [comment]
@zapik try again, build https://travis-ci.org/larshp/abaplint successful

**Comment by zapik** [comment]
@larshp Now it seems fine. Thank you!
