### ISSUE TITLE
method_parameter_names rule does not work

### ISSUE THREAD

**Issue by sbcgua** [larshp/abaplint#305]
or I'm missing something ... but I retried with config from abapGit

code
```abap
class lcl_name_factory definition final.
  public section.
    class-methods get_name
      returning
        value(result_name) type string. " <<<<<<<<<<<
endclass.
class lcl_name_factory implementation.
  method get_name.
   result_name = 'Abaper'.
  endmethod.
endclass.
```

abaplint.json
```json
{
  "global": {
    "version": "v702"
  },
  "rules": {
    "start_at_tab": {
      "enabled": true
    },
    "method_parameter_names": {
      "enabled": true,
      "ignoreExceptions": true,
      "importing": "^I._.*$",
      "returning": "^R._.*$",
      "changing": "^C._.*$",
      "exporting": "^E._.*$"
    }
  }
}
```
output
```
$ abaplint src/xxx.prog.abap
src/xxx.prog.abap[9, 4] - Start statement at tab position
abaplint: 1 issue(s) found
```
Expected is also message for `result_name`

**Comment by larshp** [comment]
local classes fixed in https://github.com/larshp/abaplint/commit/af8f7322a10348d43d1c29fe890214df8443a93d

note that local interfaces are currently not checked

**Comment by larshp** [comment]
1.5.8 released

**Comment by sbcgua** [comment]
seems to have issues (after recompile :))) )

```
$ abaplint src/zabaplinted_sample_include.prog.abap
TypeError: Cannot read property 'indexOf' of undefined
    at MethodParameterNames.checkParameter (...\abaplint\build\src\rules\method_parameter_names.js:86:39)
    at MethodParameterNames.checkMethod (...\abaplint\build\src\rules\method_parameter_names.js:67:35)
    at MethodParameterNames.run (...\abaplint\build\src\rules\method_parameter_names.js:56:47)
    at Registry.findIssues (...\abaplint\build\src\registry.js:132:45)
    at run (...\abaplint\build\src\cli.js:129:43)
    at process._tickCallback (internal/process/next_tick.js:68:7)
    at Function.Module.runMain (internal/modules/cjs/loader.js:744:11)
    at startup (internal/bootstrap/node.js:285:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:739:3)
```

```
$ cat src/zabaplinted_sample_include.prog.abap      
class lcl_name_factory definition final.            
  public section.                                   
    class-methods get_greeting                      
      importing                                     
        the_name type string                        
      returning                                     
        value(the_greeting) type string.            
endclass.                                           
class lcl_name_factory implementation.              
  method get_greeting.                              
   the_greeting = |Hello { the_name }|.             
  endmethod.                                        
endclass.                                                                           
```

**Comment by larshp** [comment]
hmm, seems to work here,
![image](https://user-images.githubusercontent.com/5888506/50419833-4544c580-0833-11e9-8637-3b5d0b026958.png)

**Comment by sbcgua** [comment]
OK, seems like I found the case. If I remove "ignoreNames ..." it dumps (can open another issue if it's a bug)

![image](https://user-images.githubusercontent.com/15635498/50420873-49c4aa80-0842-11e9-916f-1418a45c0eb6.png)

P.S. BTW is there any good docs on available rules and params for them ?

**Comment by larshp** [comment]
raising error now, see https://github.com/larshp/abaplint/commit/7475a5842c36527a46f73aec1c44b0ead5fa0ee0

run `abaplint -d` to get the default configuration, it shows all rules and config options

**Comment by larshp** [comment]
note that I break things in abaplint regularly, due to heavy refactoring, suggest fixing package.json to a specific version in order not to disturb too much

**Comment by sbcgua** [comment]
ok, closing then, the issue itself is resolve. Thanks !

P.S. on docs: well, not all of them self descriptive ... it would be nice to have some doc. I'm writing a small post on abaplint topic :) so some new users may come by.

**Comment by larshp** [comment]
docs: yeah, I'm just lazy 😄 and need to find the right setup, perhaps adding the markdown inside the rules like tslint, https://github.com/palantir/tslint/blob/master/src/rules/alignRule.ts#L39

**Comment by sbcgua** [comment]
yeap, that would be quite convenient :)

**Comment by larshp** [comment]
oh, btw. I have it on my Christmas todo list to get https://github.com/apps/abaplint working properly

GitHub is stupid and does not add the Checks API for pull requests from the outside, so I'll make it trigger on some different events
