### ISSUE TITLE
file count output

### ISSUE THREAD

**Issue by sbcgua** [larshp/abaplint#306]
abaplint does not output any stats about number of checked files.
this can be confusing as there is no control if it checked all the needed files or not. What if the path param was specified wrongly.

**Comment by larshp** [comment]
fixed in https://github.com/larshp/abaplint/commit/6b72917b30438b2e2bd7d8b359c4ee7593be7964

**Comment by sbcgua** [comment]
same here, forgot to recompile, sorry. Work fine !

Sample
```
abaplint: 0 issue(s) found, 1 file(s) analyzed
```
