### ISSUE TITLE
Version mismatch

### ISSUE THREAD

**Issue by sbcgua** [larshp/abaplint#307]
![image](https://user-images.githubusercontent.com/15635498/50419210-42000880-0838-11e9-8751-a7137d34d399.png)

P.S. maybe read package.json directly for "-v" option ?

**Comment by sbcgua** [comment]
sorry, my mistake, had to recompile 

P.S. hmm, is there some npm prelink script ?

**Comment by larshp** [comment]
run `npm test`, it takes the version from package.json and puts it into the build

https://github.com/larshp/abaplint/blob/master/version.sh
