### ISSUE TITLE
Debugging Typescript on Chrome

### ISSUE THREAD

**Issue by Gelbfuesler** [larshp/abaplint#311]
Hi, 
I am an ABAP-developer and want to dive deeper in the parser-part of the code.
Unfortunately I did not manage to get Chrome-Debugging Typescript correctly (Sourcemaps  are found, but breakpoints are ignored). Is there a setting to be obeyed?
How did you generate the Classes for the parser? By hand? Or did you parse the ABAP-BNFs? Were can I find those?
questions over questions...
kind regards Steffen

**Comment by larshp** [comment]
everything is by hand, there is no ABAP-BNF, plus the parser combinator is also custom

**Comment by larshp** [comment]
I dont use the debugger much, but suggest using https://code.visualstudio.com, it has lots of nice features + guides online

**Comment by larshp** [comment]
there are lots of bugs in the syntax, pull requests welcome. Also there is full backtracking in the parser, which makes it slow, lost of room for improvements

**Comment by larshp** [comment]
@Gelbfuesler any luck, can we close the issue?
