### ISSUE TITLE
Minor issues

### ISSUE THREAD

**Issue by FreHu** [larshp/abaplint#329]
- squiggle should only underline the lowercase keywords, not the rest of the line
- FIELD-SYMBOL not higlighted

![image](https://user-images.githubusercontent.com/5097067/51200399-ad01a400-18f9-11e9-81c7-aaa7f2e92e15.png)

**Comment by larshp** [comment]
highlighting in the playground is done by https://github.com/larshp/codemirror-abap

squiggle, yeah, its just nice to have, shift+f1 should work in the playground

**Comment by larshp** [comment]
this should fix it, there are more rules which needs adjustments, but *shrug*

**Comment by larshp** [comment]
![image](https://user-images.githubusercontent.com/5888506/59973999-022b9b00-95a7-11e9-9171-c881bb7b1578.png)
