### ISSUE TITLE
Errors in global exception constructor

### ISSUE THREAD

**Issue by sbcgua** [larshp/abaplint#336]
AL argues about generated constructor code but I don't have control over.
Maybe I'm doing something wrong ... 

![image](https://user-images.githubusercontent.com/15635498/51402713-e71bb180-1b56-11e9-8905-cfef5e873d47.png)

![image](https://user-images.githubusercontent.com/15635498/51402760-13373280-1b57-11e9-9274-f1e881b37b63.png)

**Comment by larshp** [comment]
try updating your `abaplint.json` to latest defaults, there are configuration options like https://github.com/larshp/abapGit/blob/master/abaplint.json#L99

**Comment by sbcgua** [comment]
👍 Helped :)
But now there are more errors:

![image](https://user-images.githubusercontent.com/15635498/51403662-c86aea00-1b59-11e9-9327-453740ac7724.png)

**Comment by larshp** [comment]
yeah, abaplint is moving towards syntax checking the code

disable rules `superclass_final` and `check_variables`

**Comment by larshp** [comment]
have you tried the GitHub App? https://github.com/apps/abaplint

**Comment by sbcgua** [comment]
yeah, better, thanks. 
Trying to activate linter for mockup_loader ... but there are many messages :) and some of them probably should be fixed, but I'm lazy today, this was supposed to be a very quick fix and now spent over an hour :))))

abaplint app: yes, probably I'll try it now instead of travis.

**Comment by sbcgua** [comment]
activated App.
Is it supposed to work only for PRs ? Or can be run for existing branch (master) ?

**Comment by sbcgua** [comment]
anyway, the subject is resolved so closing ... thanks !

**Comment by larshp** [comment]
app: it runs for both PRs and pushes to master, with annotations via the Checks API, so it helps a bit more than the raw list
