### ISSUE TITLE
rule object_naming does not find issue

### ISSUE THREAD

**Issue by GoWale** [larshp/abaplint#348]
I have tested some namespace developments with abaplint just to check for version issues.
And so i noticed that the rule object_naming seems not to work.
it was active in me local configuration.

At first, I was not sure if i broke the regex so I turned it back to the default.
But also, there was no error although the namespace object do not match ^Z...

**Comment by larshp** [comment]
fixing

**Comment by GoWale** [comment]
Works now for me.
thx
