### ISSUE TITLE
various parser errors, OPEN DATASET

### ISSUE THREAD

**Issue by larshp** [larshp/abaplint#370]
see https://gist.github.com/flaiker/41d0da3abb85d80dd875d663e8acbccb

**Comment by larshp** [comment]
@flaiker try again, latest version

**Comment by flaiker** [comment]
That fixed all of them. The only parser error I have left in that repository is for this statement:
```abap
TRANSFER iv_text TO iv_path NO END OF LINE.
```

**Comment by larshp** [comment]
cool, will fix it in a bit, opened new issue for it
