### ISSUE TITLE
"Extend default" ruleset

### ISSUE THREAD

**Issue by sbcgua** [larshp/abaplint#398]
Does abaplint automatically applies rules, which were not listed in abaplint.json ?
I mean, I'm using abaplint, then a new version have a completely new rule. And I don't know it to put to abaplint.json. Will it be applied ?

If not, propose to add something like "applyDefaults" to the global section or some rulesets like in eslint (although it will be much trickier)

**Comment by larshp** [comment]
it does not apply new rules automatically

good idea

**Comment by larshp** [comment]
1.6.41 published

**Comment by larshp** [comment]
option name is `applyUnspecifiedRules`
