### ISSUE TITLE
Ignore "FUNCTION module_name" in keywords_upper

### ISSUE THREAD

**Issue by flaiker** [larshp/abaplint#399]
In ADT the function module name always gets saved in upper case and you cannot do anything about it. If you have no parameters you even get a comment included that you cannot get rid of.

I suggest to add an option to ignore this statement in keywords_upper.ts.

![image](https://user-images.githubusercontent.com/5270359/54592407-9c21fb80-4a2c-11e9-951b-43aea4b0013b.png)

The function group itself (...SAPL...) also gets generated with errors by the way (upper case identifiers and wrongly indented INCLUDE statements). But these you can manually fix.

**Comment by larshp** [comment]
1.6.41 published

**Comment by flaiker** [comment]
Thanks!
