### ISSUE TITLE
Add/subtract obsolete ? Or config for issue suppresion

### ISSUE THREAD

**Issue by sbcgua** [larshp/abaplint#40]
Hi Lars,

Thanks for the tool, it looks really interesting. :)

Why does the tool claim that add/subtract operators are obsolete. It is not mentioned in abap help. Besides add is a great alternative to increment, it's more readable and safer than a=a+1 form. 

Anyway, if kept like this, would it be possible to implement some kind of linter config to be able to supress certain errors?

**Comment by larshp** [comment]
see http://help.sap.com/abapdocu_740/en/abencalc_expresssion_guidl.htm

Its part of the big plan to have everything configurable, havent had much time lately to work on this project

have you also seen my other project https://github.com/larshp/abapOpenChecks it runs inside the system and can be cofigured

**Comment by sbcgua** [comment]
Thanks for the link! It is a pity they wouldn't introduce things like "+=" that would really help. 

OpenChecks are great. I'm considering using them for my projects actually. Thanks ! As for abaplint I found the idea of CI/codecov badges awesome that's why I'm asking.

**Comment by larshp** [comment]
:smile: 

the coverage is uploaded using https://github.com/larshp/abapCov

**Comment by sbcgua** [comment]
Yes, I know, I've seen :) BTW Would you mind if I make a 731 version (in my rep) ?

**Comment by sbcgua** [comment]
P.S. Porting codecov to 731 failed :(  cl_aucv_test_runner_coverage was introduces in 7.40.

**Comment by larshp** [comment]
no, feel free. But also feel free to submit the backport as a pull request

**Comment by larshp** [comment]
closing this issue

for the backport of abapCov I've created https://github.com/larshp/abapCov/issues/6 as a reminder, I'll probably not be looking into it anytime soon
