### ISSUE TITLE
Contains non 7 bit ascii character

### ISSUE THREAD

**Issue by ElNovi** [larshp/abaplint#76]
This is quite common error message for me. I work in czech company so we use czech language for comments.  Can you please disable ascii check for commented code? Thanks

**Comment by larshp** [comment]
I have a plan to add the possibility to add a configuration file, where checks can be configured and enabled/disabled. However it is not implemented yet.

Looking at the other issue I guess you are running the checks inside the Atom editor? 

Do you use abapGit along with Atom? I'm thinking if the best solution would be to add the possibility to configure the checks inside Atom settings, or read the configuration from a file in the project.

**Comment by ElNovi** [comment]
I don't use abapGit (but i will look at it), just copied code from few transactions to Atom to see how it works. 

Configuration inside Atom might be slightly better idea.

**Comment by larshp** [comment]
abaplint is in its early stages, so there is still a lot of ideas that I would like to implement.

Configuration inside Atom: 
think it should first look for a abaplint.json configuration file by default, if not found it should be possible to configure inside Atom. Plus it should also be possible to override the configuration file inside Atom.

**Comment by larshp** [comment]
try again, I've added configuration in the Atom package(linter-abaplint 0.10.0). It allows for enabling and disabling the checks.

Ignoring just comments is a bit more work, since the rule works on the raw source code instead of statements.

![image](https://cloud.githubusercontent.com/assets/5888506/17780852/2b9976d2-656d-11e6-96b1-c40d2bf168b9.png)

**Comment by ElNovi** [comment]
Excellent work! Works really well, thanks a lot!
